title: Siam's Mind Grapes
description: Personal blog
author: Siam
github: https://github.com/aumisb
about: I'm a process controls engineer/data scientist. I am passionate about automation and a serial tinkerer with "humble" homelab.
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/siamaumi/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/aumisb"

# share:
  # twitter_username: github.io
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://aumisb.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
